"""Runs the Linear Regression Engine's 3-phase diagnostics suite
(``linear_regression.target_diagnostics`` / ``.feature_diagnostics`` /
``.residual_diagnostics``) against real OANDA historical data and writes
the three markdown reports each phase's module docstring promises:

    TARGET_ANALYSIS_REPORT.md    -- Phase 1, per-target statistical audit
    FEATURE_DIAGNOSTICS_REPORT.md -- Phase 2, per-target feature audit
    RESIDUAL_ANALYSIS_REPORT.md  -- Phase 3, per-target residual audit

All three modules were implemented and unit-tested but never run
end-to-end or wired into a report -- this script is that missing step,
mirroring the existing ``scripts/feature_correlation_analysis.py`` pattern
(fetch real candles, compute statistics, write output, never touch a
trained model's point estimate).

Usage (from the project root, with a configured .env -- see
examples/live_oanda_test.py for credential setup)::

    .venv\\Scripts\\python.exe scripts\\generate_regression_diagnostics_report.py
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "examples"))

from ml_pipeline import DatasetBuilder, TimeSeriesSplitter  # noqa: E402
from ml_pipeline.config import DatasetConfig as MLDatasetConfig  # noqa: E402
from ml_pipeline.dataset_builder import Dataset  # noqa: E402
from ml_pipeline.label_generator import REGRESSION_REGISTRY as NATIVE_REGISTRY  # noqa: E402
from ml_pipeline.splitter import SplitResult  # noqa: E402
from oanda_client import BASE_URL, PRACTICE, fetch_candles  # noqa: E402
from training.config import TrainingConfig  # noqa: E402

from linear_regression import RegressionConfig, RegressionEngine  # noqa: E402
from linear_regression.feature_diagnostics import FeatureAuditReport, audit_features_for_target  # noqa: E402
from linear_regression.inference import RegressionInferencePipeline  # noqa: E402
from linear_regression.residual_diagnostics import ResidualDiagnostics, analyze_residuals  # noqa: E402
from linear_regression.target_diagnostics import TargetDiagnostics, analyze_all_targets  # noqa: E402

OUTPUT_ROOT = ROOT / "lr_output"

#: The 8 targets with a named slot on RegressionPrediction (same set
#: examples/linear_regression_example.py trains).
NAMED_TARGETS = [
    "next_close", "next_high", "next_low", "next_return",
    "expected_pip_movement", "future_volatility",
    "maximum_favorable_excursion", "maximum_adverse_excursion",
]


def _fmt(value: float | None, decimals: int = 4) -> str:
    if value is None or not np.isfinite(value):
        return "n/a"
    return f"{value:.{decimals}f}"


# --------------------------------------------------------------------------- #
# Phase 1 -- TARGET_ANALYSIS_REPORT.md
# --------------------------------------------------------------------------- #
def render_target_report(diagnostics: Dict[str, TargetDiagnostics]) -> str:
    lines = [
        "# Target Analysis Report",
        "",
        "Phase 1 of the Linear Regression Engine diagnostics suite -- "
        "per-target statistical audit (`linear_regression.target_diagnostics`), "
        "generated by `scripts/generate_regression_diagnostics_report.py` "
        "against real OANDA EUR/USD M5 candles. Read-only: nothing here "
        "trains a model or alters a target's computation.",
        "",
        "| Target | n | Mean | Std | Skew | Kurtosis | Outliers % | ADF stat | Stationary (5%) | Top correlated feature |",
        "|---|---:|---:|---:|---:|---:|---:|---:|:---:|---|",
    ]
    for name, d in diagnostics.items():
        top_feat = f"{d.top_correlated_features[0][0]} (r={d.top_correlated_features[0][1]:+.3f})" if d.top_correlated_features else "n/a"
        lines.append(
            f"| {name} | {d.n_samples} | {_fmt(d.mean)} | {_fmt(d.std)} | {_fmt(d.skewness)} | "
            f"{_fmt(d.kurtosis)} | {_fmt(d.outlier_percentage, 2)} | {_fmt(d.stationarity.adf_statistic)} | "
            f"{'yes' if d.stationarity.is_stationary_5pct else 'no'} | {top_feat} |"
        )

    lines += ["", "## Per-target detail", ""]
    for name, d in diagnostics.items():
        lines += [
            f"### `{name}`",
            "",
            f"- Range: [{_fmt(d.minimum)}, {_fmt(d.maximum)}], median={_fmt(d.median)}, "
            f"IQR=[{_fmt(d.q25)}, {_fmt(d.q75)}]",
            f"- Missing: {_fmt(d.missing_percentage, 2)}%",
            f"- Augmented Dickey-Fuller: statistic={_fmt(d.stationarity.adf_statistic)}, "
            f"critical values={d.stationarity.critical_values}, "
            f"n_lags={d.stationarity.n_lags}, n_eff={d.stationarity.n_effective_samples} -> "
            f"**{'stationary' if d.stationarity.is_stationary_5pct else 'non-stationary'} at 5%**",
            "- Top 10 correlated features:",
        ]
        for fname, r in d.top_correlated_features[:10]:
            lines.append(f"  - `{fname}`: r={r:+.4f}")
        lines.append("")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Phase 2 -- FEATURE_DIAGNOSTICS_REPORT.md
# --------------------------------------------------------------------------- #
def render_feature_report(audits: Dict[str, FeatureAuditReport]) -> str:
    lines = [
        "# Feature Diagnostics Report",
        "",
        "Phase 2 of the Linear Regression Engine diagnostics suite -- "
        "per-target feature audit (`linear_regression.feature_diagnostics`): "
        "Pearson/Spearman/mutual information vs. each target, Variance "
        "Inflation Factor, near-constant features, and highly correlated "
        "pairs. Recommendations only -- nothing here removes a feature.",
        "",
    ]
    for target, audit in audits.items():
        high_vif = sorted(
            ((n, v) for n, v in audit.vif.items() if np.isfinite(v) and v > 10.0),
            key=lambda kv: kv[1], reverse=True,
        )
        top_mi = sorted(audit.mutual_information.items(), key=lambda kv: kv[1], reverse=True)[:10]
        lines += [
            f"## Target: `{target}`",
            "",
            f"- Near-constant features (all targets, same list): {len(audit.near_constant)}",
            f"- High-VIF features (VIF > 10): {len(high_vif)}",
            f"- Highly correlated pairs (|Pearson| >= 0.95): {len(audit.high_correlation_pairs)}",
            "",
            "**Top 10 features by mutual information:**",
            "",
            "| Feature | MI (nats) | Pearson | Spearman | VIF | Importance |",
            "|---|---:|---:|---:|---:|---:|",
        ]
        for fname, mi in top_mi:
            lines.append(
                f"| `{fname}` | {_fmt(mi)} | {_fmt(audit.pearson.get(fname))} | "
                f"{_fmt(audit.spearman.get(fname))} | {_fmt(audit.vif.get(fname), 2)} | "
                f"{_fmt(audit.feature_importance.get(fname))} |"
            )
        lines += ["", "**Recommendations:**", ""]
        for rec in audit.recommendations:
            lines.append(f"- {rec}")
        lines.append("")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Phase 3 -- RESIDUAL_ANALYSIS_REPORT.md
# --------------------------------------------------------------------------- #
def render_residual_report(diagnostics: Dict[str, ResidualDiagnostics]) -> str:
    lines = [
        "# Residual Analysis Report",
        "",
        "Phase 3 of the Linear Regression Engine diagnostics suite -- "
        "per-target residual audit (`linear_regression.residual_diagnostics`) "
        "over each target's held-out test-split predictions: normality "
        "(Shapiro-Wilk / Jarque-Bera / Q-Q), heteroscedasticity "
        "(Breusch-Pagan), autocorrelation (Durbin-Watson), and a market-regime "
        "error breakdown.",
        "",
        "| Target | Mean resid | Std resid | Normal (5%) | Heteroscedastic (5%) | Durbin-Watson |",
        "|---|---:|---:|:---:|:---:|---:|",
    ]
    for name, d in diagnostics.items():
        lines.append(
            f"| {name} | {_fmt(d.residual_statistics['mean'])} | {_fmt(d.residual_statistics['std'])} | "
            f"{'yes' if d.normality.is_normal_5pct else 'no'} | "
            f"{'yes' if d.heteroscedasticity.is_heteroscedastic_5pct else 'no'} | "
            f"{_fmt(d.durbin_watson)} |"
        )

    lines += ["", "## Per-target detail", ""]
    for name, d in diagnostics.items():
        lines += [
            f"### `{name}`",
            "",
            f"- Shapiro-Wilk: stat={_fmt(d.normality.shapiro_statistic)}, p={_fmt(d.normality.shapiro_pvalue)}; "
            f"Jarque-Bera: stat={_fmt(d.normality.jarque_bera_statistic)}, p={_fmt(d.normality.jarque_bera_pvalue)} "
            f"-> **{'normal' if d.normality.is_normal_5pct else 'non-normal'} at 5%**",
            f"- Q-Q correlation: {_fmt(d.qq.qq_correlation)} (n={d.qq.n_points})",
            f"- Breusch-Pagan: LM={_fmt(d.heteroscedasticity.lm_statistic)}, p={_fmt(d.heteroscedasticity.lm_pvalue)} "
            f"-> **{'heteroscedastic' if d.heteroscedasticity.is_heteroscedastic_5pct else 'homoscedastic'} at 5%**",
            f"- Durbin-Watson: {_fmt(d.durbin_watson)} "
            "(~2.0 = no autocorrelation, <2 = positive, >2 = negative)",
            "- Regime breakdown (MAE / RMSE):",
        ]
        for regime, stats_ in d.regime_breakdown.items():
            if stats_.get("mae") is None:
                lines.append(f"  - {regime}: n={stats_['n_samples']} ({stats_.get('note', 'n/a')})")
            else:
                lines.append(
                    f"  - {regime}: n={stats_['n_samples']}, MAE={_fmt(stats_['mae'])}, RMSE={_fmt(stats_['rmse'])}"
                )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    print(f"OANDA environment : {'PRACTICE' if PRACTICE else 'LIVE'} ({BASE_URL})")
    symbol, timeframe = "EUR_USD", "M5"
    candles = fetch_candles(symbol, timeframe, count=2500)
    print(f"Fetched {len(candles)} live candles ({candles['timestamp'].iloc[0]} -> {candles['timestamp'].iloc[-1]})")

    window_size, horizon, stride = 250, 5, 3
    native_targets = [t for t in NAMED_TARGETS if t in NATIVE_REGISTRY]
    ml_cfg = MLDatasetConfig(
        window_size=window_size, horizon=horizon, stride=stride, symbol=symbol, timeframe=timeframe,
        regression_targets=native_targets,
    )
    print(f"\nBuilding dataset: window_size={window_size}, horizon={horizon}, stride={stride}...")
    dataset: Dataset = DatasetBuilder(ml_cfg).build(candles)
    print(f"Built {len(dataset)} samples x {dataset.X.shape[1]} features")

    split: SplitResult = TimeSeriesSplitter(method="simple", train_frac=0.7, val_frac=0.15).split(len(dataset))[0]
    print(f"Split -> train={len(split.train_idx)} val={len(split.val_idx)} test={len(split.test_idx)}")

    training_config = TrainingConfig(
        experiment_name="lr_diagnostics_eurusd_m5", feature_version="1.0.0", dataset_version="1.0.0",
        strategy_version="1.0.0", output_root=str(OUTPUT_ROOT), scaler="standard", random_seed=42,
    )
    regression_config = RegressionConfig(
        targets=NAMED_TARGETS, prediction_horizon=horizon, model_type="ridge",
        model_hyperparameters={"alpha": 1.0}, n_bootstrap=15, pip_size=0.0001,
        symbol=symbol, timeframe=timeframe, training_config=training_config,
    )

    engine = RegressionEngine(regression_config)
    print(f"\nTraining {len(NAMED_TARGETS)} independent linear models (one per target)...")
    records = engine.train(dataset, split, raw_df=candles)
    for target, record in records.items():
        m = record.testing_metrics
        print(f"  {target:<28} test R2={m['r2']:.3f} test RMSE={m['rmse']:.6f}")

    # --- Phase 1: per-target statistical audit ------------------------------ #
    print("\nPhase 1 -- target diagnostics...")
    target_diag = analyze_all_targets(dataset.y_reg, dataset.X, dataset.feature_names)

    # --- Phase 2: per-target feature audit ----------------------------------- #
    print("Phase 2 -- feature diagnostics...")
    feature_audits = {
        target: audit_features_for_target(dataset.X, dataset.y_reg[target], dataset.feature_names, target)
        for target in NAMED_TARGETS
    }

    # --- Phase 3: per-target residual audit (real test-split predictions) --- #
    print("Phase 3 -- residual diagnostics...")
    X_test = dataset.X[split.test_idx]
    feature_names = dataset.feature_names
    residual_diag: Dict[str, ResidualDiagnostics] = {}
    for target, record in records.items():
        pipeline = RegressionInferencePipeline(
            record.artifact_dir, feature_version=training_config.feature_version, strict=True,
        ).load()
        point, _std = pipeline.predict(X_test, feature_names)
        y_pred = point.ravel()
        y_true = dataset.y_reg[target][split.test_idx]
        residual_diag[target] = analyze_residuals(target, y_true, y_pred, X_test, feature_names)

    # --- Write the three reports --------------------------------------------- #
    (ROOT / "TARGET_ANALYSIS_REPORT.md").write_text(render_target_report(target_diag), encoding="utf-8")
    (ROOT / "FEATURE_DIAGNOSTICS_REPORT.md").write_text(render_feature_report(feature_audits), encoding="utf-8")
    (ROOT / "RESIDUAL_ANALYSIS_REPORT.md").write_text(render_residual_report(residual_diag), encoding="utf-8")

    print("\nWrote:")
    print(f"  {ROOT / 'TARGET_ANALYSIS_REPORT.md'}")
    print(f"  {ROOT / 'FEATURE_DIAGNOSTICS_REPORT.md'}")
    print(f"  {ROOT / 'RESIDUAL_ANALYSIS_REPORT.md'}")


if __name__ == "__main__":
    main()
